- .github/workflows/nightly-forc-release.yml
- .github/workflows/nightly-fuel-core-release.yml
- .github/workflows/scripts/write-release-notes.sh
The workflow current does `git log --oneline` to fetch commits to master, and this is just text. This PR just formats the text so that they link directly to the PRs/commits, like so:
Example:
- [4fe1949e6](https://github.com/FuelLabs/sway/commit/4fe1949e6) Use zero and one registers instead of 0/1 immediates [#2621](https://github.com/FuelLabs/sway/pull/2621)
- [1549bab1c](https://github.com/FuelLabs/sway/commit/1549bab1c) Fix `storage` blocks [#2618](https://github.com/FuelLabs/sway/pull/2618)
- [f7b346eb4](https://github.com/FuelLabs/sway/commit/f7b346eb4) fix: ForwardSlash span collection [#2625](https://github.com/FuelLabs/sway/pull/2625)
> ci/feat: pr and commit links for release notes

- .github/workflows/nightly-forc-release.yml
- .github/workflows/nightly-fuel-core-release.yml
One last change to remove hyphens from dates to comply with semver: https://semver.org/#spec-item-10
> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version...
The previous versions were __not__ semver compliant, since the build metadata was (example) `nightly.2022-09-15.abcdefg` - the date should not be separated by hyphens.
> Remove hyphen from dates to comply with semver

- .github/workflows/nightly-forc-client-release.yml
- .github/workflows/nightly-forc-release.yml
- .github/workflows/nightly-fuel-core-release.yml
From the git book:
> Generally, eight to ten characters are more than enough to be unique within a project. For example, as of February 2019, the Linux kernel (which is a fairly sizable project) has over 875,000 commits and almost seven million objects in its object database, with no two objects whose SHA-1s are identical in the first 12 characters.
source: https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#Short-SHA-1
Technically its unlikely we run into hash collisions, but its still nice to fix our commit hash within the build metadata to a sensible length. In this case I simply chose the maximum of the recommended 8-10 characters.
> set git short sha length to 10

- .github/workflows/nightly-forc-release.yml
mistakenly installed and built `forc-doc` twice: https://github.com/FuelLabs/sway-nightly-binaries/actions/runs/4039351047/jobs/6944001587
also added `--locked` to `cross build`.
> fix: build with --locked, remove forc-doc installation

- .github/workflows/nightly-fuel-core-release.yml
Removes `protoc` which is not required anymore and adds `wasm32` to fix builds failures. Thanks @xgreenx :)
> fix: add `wasm32` to installed toolchains for fuel-core nightly builds

- .github/workflows/nightly-fuel-core-release.yml
Pins rust version to 1.76.0 for fuel-core builds
> ci: use rust v1.76.0 for fuel-core builds

- .github/workflows/create-release.yml
- .github/workflows/nightly-fuel-core-release.yml
The CI builds have been failing for x86 macos because of this error:
```
info: note that the toolchain '1.75.0-aarch64-apple-darwin' is currently in use (overridden by '/Users/runner/work/sway-nightly-binaries/sway-nightly-binaries/rust-toolchain.toml')
...
error[E0463]: can't find crate for `core`
|
= note: the `x86_64-apple-darwin` target may not be installed
= help: consider downloading the target with `rustup target add x86_64-apple-darwin`
```
This is because the rust version doesn't match the version in the newly added toolchain toml file in fuel core: https://github.com/FuelLabs/fuel-core/blob/master/rust-toolchain.toml
So the `x86_64-apple-darwin` is installed for the wrong version, and not used at build time. I believe by fixing the version to match what's in fuel-core, the …
> fix: Update rust version for fuel-core

- .github/workflows/create-release.yml
- .github/workflows/nightly-forc-explorer-release.yml
- .github/workflows/nightly-forc-release.yml
- .github/workflows/nightly-forc-wallet-release.yml
- .github/workflows/nightly-fuel-core-release.yml
To prevent the notification steps from being skipped on failure, this PR adds `if: always()` to ensure the step is always run.
> ci: ensure the notify step is run on failure

- .github/workflows/nightly-forc-explorer-release.yml
- .github/workflows/nightly-forc-release.yml
- .github/workflows/nightly-forc-wallet-release.yml
- .github/workflows/nightly-fuel-core-release.yml
The previous setup didn't work because the notification action only works on linux and the job was part of an OS matrix. It should be sufficient to run the job only on `create-release` which depends on the others.
> ci: only notify on the top level workflow

- .github/workflows/create-release.yml
This job previously only ran if everything succeeded, which was not the intention. Adding `always()` so it will not be skipped after a failure.
> ci: add always() to monitor-release job

- .github/workflows/nightly-forc-release.yml
closes #54.
About https://github.com/FuelLabs/fuelup/pull/689#issuecomment-2479073484. This fixes #54 by adding forc-submit to the list of released binaries.
> fix: add missing `forc-submit` to list of released binaries

- .github/CODEOWNERS
Tooling maintains this repo but it doesn't own the code so reviews are not asked for automatically. This PR fixes this by adding tooling as owner of all files in this repo.
> chore: add tooling as codeowners for the repo

- .github/workflows/create-release.yml
- .github/workflows/nightly-forc-explorer-release.yml
- .github/workflows/nightly-forc-release.yml
- .github/workflows/nightly-forc-wallet-release.yml
- .github/workflows/nightly-fuel-core-release.yml
GitHub's actions/upload-release-assets is no longer maintained and seems to repeatedly break (e.g. SSLV3_ALERT_BAD_RECORD_MAC), so I suggest moving to a highly active and up to date runner.
> chore: swap deprecated actions/upload-release-assets to softprops/action-gh-release

- .github/workflows/nightly-fuel-core-release.yml
Bumps rust version used for fuel-core builds to 1.79 to match https://github.com/FuelLabs/fuel-core/blob/master/rust-toolchain.toml.
> chore: use rust v1.79.0 while building fuel-core

- .github/workflows/nightly-forc-explorer-release.yml
- .github/workflows/nightly-forc-release.yml
- .github/workflows/nightly-forc-wallet-release.yml
- .github/workflows/nightly-fuel-core-release.yml
The nightly run pushes releases on the master branch, not tags.
> Nightly jobs are performed on master

- .github/workflows/nightly-forc-explorer-release.yml
- .github/workflows/nightly-forc-release.yml
- .github/workflows/nightly-forc-wallet-release.yml
- .github/workflows/nightly-fuel-core-release.yml
GitHub releases only work on tags, so checkout the tag before pushing.
> Checkout the tag on release

- .github/workflows/nightly-forc-explorer-release.yml
- .github/workflows/nightly-forc-release.yml
- .github/workflows/nightly-forc-wallet-release.yml
- .github/workflows/nightly-fuel-core-release.yml
Nightly builds are done on master, not on tags.
So let's enforce master to have a tag on build.
> Enforce git tag on master releases

- .github/workflows/create-release.yml
- .github/workflows/nightly-forc-explorer-release.yml
- .github/workflows/nightly-forc-release.yml
- .github/workflows/nightly-forc-wallet-release.yml
- .github/workflows/nightly-fuel-core-release.yml
All the previous changes today were pushing to the wrong places...
- `sway-nightly-binaries` is where each nightly release lives
- `sway-nightly-binaries` has the `nightly-` tags
- `sway-nightly-binaries` has the builds output of `forc-explorer`, `forc`, `forc-wallet`, and `fuel-core`
- All of the non-`sway-nightly-binaries` repos have their own tags in the form `vX.Y.Z`
On build, if it's `master` we need to create a tag because `softprops/action-gh-release@v2` requires one.
For all the sub-repo builds, when done, push to /this/ release target (tag).
> Create tag on repo, push to release from other repos

- .github/workflows/create-release.yml
- .github/workflows/nightly-forc-explorer-release.yml
- .github/workflows/nightly-forc-release.yml
- .github/workflows/nightly-forc-wallet-release.yml
- .github/workflows/nightly-fuel-core-release.yml
Now that we're now using the proper release tag (i.e `create-release.outputs.release_name`) downstream, I think enforcing the branch on master isn't actually needed.
The original issue was that we were skipping builds when the tag was not set, which is why I was trying to force `master` to have a tag. But I'm now thinking that what that error message actually said was that the `tag_name` parameter to `softprops/action-gh-release@v2` was empty.
It's set now, and to the correct value `create-release.outputs.release_name`, so this should now be pushing to the correct place.
> Remove master tag now correct release name is used

- .github/workflows/nightly-forc-release.yml
Adds forc-node to the list of binaries included in nightly builds.
> add: forc-node to nightly builds

- .github/workflows/nightly-forc-release.yml
- .github/workflows/nightly-fuel-core-release.yml
- .github/workflows/setup-cross-build.yml
Fixes build [failures ](https://github.com/FuelLabs/sway-nightly-binaries/actions/runs/17480050315) introduced by https://github.com/FuelLabs/sway/pull/7353 which added `fuel-core` as a dependency to the sway repo. We now have adopted `fuel-core`'s cross-compilation workflow to resolve `libclang` version conflicts and missing Rust target installations.
> fix: centralize cross-compilation setup to resolve build errors

- .github/workflows/nightly-forc-release.yml
- .github/workflows/nightly-fuel-core-release.yml
Nightly workflows failed with “Can’t find action.yml … Did you forget to run actions/checkout …” because the job checked out another repo over the workspace before calling the local composite action.
Fix: checkout this repo first (to provide ./.github/actions/setup-cross-build), then checkout the target repo into sources/, and call the composite via local path.
> fix composite action resolution by checking out repo first and building from sources

- .github/actions/setup-cross-build/action.yml
- .github/workflows/nightly-forc-release.yml
- .github/workflows/nightly-fuel-core-release.yml
Making progress but running into new [failures](https://github.com/FuelLabs/sway-nightly-binaries/actions/runs/17541292686/job/49813366875) which this PR aims to address. 
overview:
- Install build-essential/clang/libclang-dev/pkg-config/cmake/libssl-dev/zlib1g-dev (native Linux and via Cross.toml pre-build) so libc headers and modern libclang are available.
- Fixes librocksdb-sys/clang-sys failures (stdarg.h missing, libclang 3.8.x).
- bumps rust version from 1.81 to 1.86 for fuel-core to [match](https://github.com/FuelLabs/fuel-core/blob/33238c6e10b0d72fd4f490c854afa414adef1f02/Cargo.toml#L53C1-L53C24) their repo
> ci: setup-cross-build — add Cross.toml + Linux build deps
